apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-ai-compliance.fullname" . }}-sanitizer
  labels:
    {{- include "kong-ai-compliance.labels" . | nindent 4 }}
    app.kubernetes.io/component: pii-sanitizer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "kong-ai-compliance.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pii-sanitizer
